### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#1]
# Motivation

It is clear that tensorflow's 1.0 -> 2.0 upgrade has severely limited the portability of the DeepForest package (https://travis-ci.org/github/weecology/DeepForest/builds/749697379). While it may be possible to continue to support tensorflow as the primary machine learning engine, the vast majority of code in this project is agnostic to the model prediction step. Judging from 

https://github.com/fizyr/keras-retinanet/issues/1471. The object detection model that underlies the tensorflow version doesn't have long to live. 

As an aside, I like many people, want to thank @hgaiser for his work in leading the keras-retinanet repo. 

Given that we have a number of research goals that relate to this model, it seems like the sooner we decide on a pathway forward the better. This repo and issue will serve as a central place for DeepForest users to see the status of moving towards pytorch.  As a starting place I've copied the code from the DeepForest repo and will slowly work to replace the components. 

# Milestones

- [x] Swap pytorch for tensorflow dependencies and setup travis tests.
- [x] Replace prediction and training scripts with pytorch implementations
- [x] Replace tfrecord generation. This needs more thought, its not immediately obvious how to store the over 20 million pretraining images for semi-supervision.

**Comment by bw4sz** [comment]
Closing this issue at the end of milestone in favor of creating more detailed issues to bring the package forward.
